# create a docker-compose.yml file with the following content
# postgres as db, auth, url-shortener, nginx as proxy

version: "3.9"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  auth:
    build:
      context: auth
      dockerfile: Dockerfile
    image: web-service/auth:v1
    environment:
      - POSTGRES_URI=${POSTGRES_URI}
      - APP_SECRET=${APP_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - EXPIRE_TIME=${EXPIRE_TIME}
    ports:
      - "3000:3000"
    depends_on:
      - db

  shortener:
    build:
      context: shortener
      dockerfile: Dockerfile
    image: web-service/shortener:v1
    environment:
      - POSTGRES_URI_SHORT=${POSTGRES_URI_SHORT}
      - AUTH_URL=${AUTH_URL}
    ports:
      - "3001:3001"
    depends_on:
      - db

  proxy:
    build:
      context: proxy
      dockerfile: Dockerfile
    image: web-service/proxy:v1
    ports:
      - "80:80"
    depends_on:
      - auth
      - shortener
